import { defineTarget, manualSetup } from '@profullstack/sh1pt-core';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

interface Config {
  packageName: string;      // e.g. "myapp"
  architecture?: ('amd64' | 'arm64' | 'armhf')[];
  distribution?: string;    // e.g. "jammy" | "noble"
  component?: string;       // e.g. "main"
  repoHost?: string;        // e.g. "apt.example.com"
  maintainer?: string;
  description?: string;
  section?: string;
  priority?: string;
  depends?: string[];
  homepage?: string;
  packageSize?: number;
  packageSha256?: string;
  packageFilename?: string;
}

function debVersion(version: string): string {
  return version.replace(/^v/, '');
}

function packageFileName(config: Config, version: string, arch: string): string {
  return config.packageFilename
    ? config.packageFilename
      .replaceAll('{{arch}}', arch)
      .replaceAll('{arch}', arch)
      .replaceAll('{{version}}', debVersion(version))
      .replaceAll('{version}', debVersion(version))
    : `pool/main/${config.packageName[0] ?? '_'}/${config.packageName}/${config.packageName}_${debVersion(version)}_${arch}.deb`;
}

function renderControl(config: Config): string {
  const arches = config.architecture ?? ['amd64', 'arm64'];
  const section = config.section ?? 'utils';
  const priority = config.priority ?? 'optional';
  const maintainer = config.maintainer ?? 'Generated by sh1pt <maintainer@example.invalid>';
  const description = config.description ?? `Release package for ${config.packageName}`;
  const lines = [
    `Source: ${config.packageName}`,
    `Section: ${section}`,
    `Priority: ${priority}`,
    `Maintainer: ${maintainer}`,
    'Standards-Version: 4.7.0',
  ];

  if (config.homepage) lines.push(`Homepage: ${config.homepage}`);

  lines.push('');
  lines.push(`Package: ${config.packageName}`);
  lines.push(`Architecture: ${arches.join(' ')}`);
  if (config.depends?.length) lines.push(`Depends: ${config.depends.join(', ')}`);
  lines.push(`Description: ${description}`);
  lines.push(' Generated by sh1pt for apt repository publishing.');
  lines.push('');
  return lines.join('\n');
}

function renderPackagesIndex(ctx: { version: string }, config: Config, arch: string): string {
  const description = config.description ?? `Release package for ${config.packageName}`;
  const lines = [
    `Package: ${config.packageName}`,
    `Version: ${debVersion(ctx.version)}`,
    `Architecture: ${arch}`,
    `Maintainer: ${config.maintainer ?? 'Generated by sh1pt <maintainer@example.invalid>'}`,
    `Filename: ${packageFileName(config, ctx.version, arch)}`,
    `Size: ${config.packageSize ?? 0}`,
    `SHA256: ${config.packageSha256 ?? 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'}`,
    `Description: ${description}`,
  ];

  if (config.depends?.length) lines.push(`Depends: ${config.depends.join(', ')}`);
  if (config.homepage) lines.push(`Homepage: ${config.homepage}`);

  lines.push('');
  return lines.join('\n');
}

export default defineTarget<Config>({
  id: 'pkg-apt',
  kind: 'package-manager',
  label: 'apt repo / PPA',
  async build(ctx, config) {
    const arches = config.architecture ?? ['amd64', 'arm64'];
    const dist = config.distribution ?? 'jammy';
    const component = config.component ?? 'main';
    const controlPath = join(ctx.outDir, 'debian', 'control');
    ctx.log(`build .deb for ${config.packageName} v${ctx.version} [${arches.join(', ')}]`);
    await mkdir(dirname(controlPath), { recursive: true });
    await writeFile(controlPath, renderControl(config), 'utf-8');

    await Promise.all(arches.map(async (arch) => {
      const packagesPath = join(ctx.outDir, 'dists', dist, component, `binary-${arch}`, 'Packages');
      await mkdir(dirname(packagesPath), { recursive: true });
      await writeFile(packagesPath, renderPackagesIndex(ctx, config, arch), 'utf-8');
    }));

    // TODO: run dpkg-buildpackage or fpm to produce .deb artifacts
    return { artifact: controlPath };
  },
  async ship(ctx, config) {
    const dist = config.distribution ?? 'jammy';
    const component = config.component ?? 'main';
    ctx.log(`publish ${config.packageName}@${ctx.version} to apt repo (${dist}/${component})`);
    if (ctx.dryRun) return { id: 'dry-run' };
    // TODO: upload .deb and update InRelease/Packages with GPG signing
    // Uses APT_GPG_KEY + APT_REPO_SSH_KEY from ctx.secret()
    return {
      id: `${config.packageName}@${ctx.version}`,
      url: `https://${config.repoHost ?? 'apt.sh1pt.com'}`,
    };
  },
  async status(id) {
    const name = id.split('@')[0] ?? id;
    return { state: 'live', url: `https://apt.sh1pt.com/pool/main/${name[0] ?? '_'}/${name}/` };
  },
  setup: manualSetup({
    label: 'apt repo / PPA',
    vendorDocUrl: 'https://wiki.debian.org/HowToSetupADebianRepository',
    steps: [
      'Generate a GPG key for signing: gpg --full-generate-key',
      'Run: sh1pt secret set APT_GPG_KEY "$(gpg --export-secret-keys --armor <key-id>)"',
      'Run: sh1pt secret set APT_GPG_PASSPHRASE <passphrase>',
      'Configure your apt repo host (S3 + CloudFront or self-hosted)',
      'Run: sh1pt secret set APT_REPO_SSH_KEY "$(cat ~/.ssh/apt_deploy_key)"',
    ],
  }),
});
