import { defineTarget, manualSetup } from '@profullstack/sh1pt-core';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { isAbsolute, join } from 'node:path';

interface Config {
  pkgName: string;           // AUR package name, e.g. "myapp-bin"
  pkgbuildTemplate?: string; // path to custom PKGBUILD template (optional)
  maintainer?: string;       // AUR maintainer name shown in PKGBUILD
  arch?: ('x86_64' | 'aarch64' | 'any')[];
  pkgrel?: number;
  pkgdesc?: string;
  url?: string;
  license?: string[];
  depends?: string[];
  optDepends?: string[];
  provides?: string[];
  conflicts?: string[];
  sourceUrl?: string;
  sourceSha256?: string;
  binaryName?: string;
  installName?: string;
}

function pkgver(version: string): string {
  return version.replace(/^v/, '').replace(/-/g, '_');
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function bashArray(values: string[]): string {
  return `(${values.map(shellQuote).join(' ')})`;
}

function srcinfoList(key: string, values: string[]): string[] {
  return values.map((value) => `\t${key} = ${value}`);
}

function assertPkgName(pkgName: string): void {
  if (!/^[a-z0-9@_+][a-z0-9@._+-]*$/.test(pkgName)) {
    throw new Error(`pkgName must be a valid Arch package name, got "${pkgName}"`);
  }
}

function sourceUrl(config: Config, ctx: { version: string }): string {
  return config.sourceUrl ?? `${config.pkgName}-${pkgver(ctx.version)}.tar.gz`;
}

function sourceSha256(config: Config): string {
  return config.sourceSha256 ?? 'SKIP';
}

function renderPkgbuild(ctx: { projectDir: string; version: string }, config: Config): string {
  assertPkgName(config.pkgName);
  const arches = config.arch ?? ['x86_64', 'aarch64'];
  const release = config.pkgrel ?? 1;
  const desc = config.pkgdesc ?? `Release package for ${config.pkgName}`;
  const licenses = config.license ?? ['custom'];
  const depends = config.depends ?? [];
  const optDepends = config.optDepends ?? [];
  const provides = config.provides ?? [];
  const conflicts = config.conflicts ?? [];
  const binaryName = config.binaryName ?? config.pkgName.replace(/-bin$/, '');
  const installName = config.installName ?? binaryName;
  const lines = [
    `# Maintainer: ${config.maintainer ?? 'Generated by sh1pt'}`,
    `pkgname=${config.pkgName}`,
    `pkgver=${pkgver(ctx.version)}`,
    `pkgrel=${release}`,
    `pkgdesc=${shellQuote(desc)}`,
    `arch=${bashArray(arches)}`,
    `url=${shellQuote(config.url ?? 'https://sh1pt.com')}`,
    `license=${bashArray(licenses)}`,
  ];

  if (depends.length) lines.push(`depends=${bashArray(depends)}`);
  if (optDepends.length) lines.push(`optdepends=${bashArray(optDepends)}`);
  if (provides.length) lines.push(`provides=${bashArray(provides)}`);
  if (conflicts.length) lines.push(`conflicts=${bashArray(conflicts)}`);

  lines.push(`source=${bashArray([sourceUrl(config, ctx)])}`);
  lines.push(`sha256sums=${bashArray([sourceSha256(config)])}`);
  lines.push('');
  lines.push('package() {');
  lines.push(`  install -Dm755 "$srcdir/${binaryName}" "$pkgdir/usr/bin/${installName}"`);
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderSrcinfo(ctx: { version: string }, config: Config): string {
  assertPkgName(config.pkgName);
  const arches = config.arch ?? ['x86_64', 'aarch64'];
  const release = config.pkgrel ?? 1;
  const desc = config.pkgdesc ?? `Release package for ${config.pkgName}`;
  const licenses = config.license ?? ['custom'];
  const lines = [
    `pkgbase = ${config.pkgName}`,
    `\tpkgdesc = ${desc}`,
    `\tpkgver = ${pkgver(ctx.version)}`,
    `\tpkgrel = ${release}`,
    `\turl = ${config.url ?? 'https://sh1pt.com'}`,
    ...srcinfoList('arch', arches),
    ...srcinfoList('license', licenses),
    ...srcinfoList('depends', config.depends ?? []),
    ...srcinfoList('optdepends', config.optDepends ?? []),
    ...srcinfoList('provides', config.provides ?? []),
    ...srcinfoList('conflicts', config.conflicts ?? []),
    `\tsource = ${sourceUrl(config, ctx)}`,
    `\tsha256sums = ${sourceSha256(config)}`,
    '',
    `pkgname = ${config.pkgName}`,
    '',
  ];
  return lines.join('\n');
}

async function renderFromTemplate(ctx: { projectDir: string; version: string }, config: Config): Promise<string> {
  assertPkgName(config.pkgName);
  const templatePath = isAbsolute(config.pkgbuildTemplate!)
    ? config.pkgbuildTemplate!
    : join(ctx.projectDir, config.pkgbuildTemplate!);
  const template = await readFile(templatePath, 'utf-8');
  return template
    .replaceAll('{{pkgName}}', config.pkgName)
    .replaceAll('{{pkgver}}', pkgver(ctx.version))
    .replaceAll('{{pkgrel}}', String(config.pkgrel ?? 1))
    .replaceAll('{{arch}}', bashArray(config.arch ?? ['x86_64', 'aarch64']))
    .replaceAll('{{source}}', bashArray([sourceUrl(config, ctx)]))
    .replaceAll('{{sha256sums}}', bashArray([sourceSha256(config)]));
}

export default defineTarget<Config>({
  id: 'pkg-aur',
  kind: 'package-manager',
  label: 'Arch User Repository (AUR)',
  async build(ctx, config) {
    assertPkgName(config.pkgName);
    const arches = config.arch ?? ['x86_64', 'aarch64'];
    const pkgbuildPath = join(ctx.outDir, 'PKGBUILD');
    const srcinfoPath = join(ctx.outDir, '.SRCINFO');
    ctx.log(`render PKGBUILD for ${config.pkgName} v${ctx.version} [${arches.join(', ')}]`);
    await mkdir(ctx.outDir, { recursive: true });
    await writeFile(pkgbuildPath, config.pkgbuildTemplate
      ? await renderFromTemplate(ctx, config)
      : renderPkgbuild(ctx, config), 'utf-8');
    await writeFile(srcinfoPath, renderSrcinfo(ctx, config), 'utf-8');
    return { artifact: pkgbuildPath };
  },
  async ship(ctx, config) {
    assertPkgName(config.pkgName);
    ctx.log(`push PKGBUILD + .SRCINFO to AUR ssh://aur@aur.archlinux.org/${config.pkgName}.git`);
    if (ctx.dryRun) return { id: 'dry-run' };
    // TODO: git clone ssh://aur@aur.archlinux.org/${pkgName}.git (using AUR_SSH_KEY secret)
    //       copy PKGBUILD + .SRCINFO, commit "upgpkg: ${pkgName} ${version}", push
    return {
      id: `${config.pkgName}@${ctx.version}`,
      url: `https://aur.archlinux.org/packages/${config.pkgName}`,
    };
  },
  async status(id) {
    const [name] = id.split('@');
    return { state: 'live', url: `https://aur.archlinux.org/packages/${name}` };
  },

  setup: manualSetup({
    label: 'Arch User Repository (AUR)',
    vendorDocUrl: 'https://wiki.archlinux.org/title/AUR_submission_guidelines',
    steps: [
      'Create an account at https://aur.archlinux.org and register an SSH key in your profile',
      'Run: sh1pt secret set AUR_SSH_KEY "$(cat ~/.ssh/id_ed25519)"  (or your AUR key)',
      'First-time publish: manually create the AUR package via `ssh aur@aur.archlinux.org` setup-repo',
      'sh1pt handles subsequent version bumps automatically (PKGBUILD render + git push)',
      'Naming convention: use <name>-bin for pre-built binaries, <name>-git for VCS packages',
    ],
  }),
});
