import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ApiIR, Operation } from '../core/types.js';

export interface GenerateTsSdkOptions {
  outDir: string;
  packageName?: string;
  // Default base URL — generated code accepts an override at construction time.
  defaultBaseUrl?: string;
}

export interface GeneratedFile {
  path: string;
  contents: string;
}

// v0 emits a single client.ts with one method per operation. Methods are
// grouped onto the class but namespaced by tag in the resource accessors at
// the bottom (`client.pets.list(...)`). Pagination, retries, and streaming
// are deliberately not generated yet — see the Stainless feature backlog.
export async function generateTsSdk(ir: ApiIR, opts: GenerateTsSdkOptions): Promise<GeneratedFile[]> {
  const files = render(ir, opts);
  await mkdir(opts.outDir, { recursive: true });
  for (const f of files) {
    await mkdir(join(opts.outDir, dirOf(f.path)), { recursive: true });
    await writeFile(join(opts.outDir, f.path), f.contents, 'utf8');
  }
  return files;
}

function render(ir: ApiIR, opts: GenerateTsSdkOptions): GeneratedFile[] {
  const baseUrl = opts.defaultBaseUrl ?? ir.servers[0] ?? 'http://localhost';
  const className = pascal(ir.title.replace(/[^a-zA-Z0-9]+/g, ' ')) + 'Client';
  const tagGroups = groupByTag(ir.operations);

  const methods = ir.operations.map(renderMethod).join('\n\n');
  const accessors = Object.entries(tagGroups)
    .map(([tag, ops]) => `  ${camel(tag)} = {\n${ops.map((o) => `    ${camel(o.id)}: this.${camel(o.id)}.bind(this),`).join('\n')}\n  };`)
    .join('\n');

  const client = `// AUTO-GENERATED by @profullstack/sh1pt-openapi/gen-sdk-ts.
// Source: ${ir.title} v${ir.version}. Do not edit by hand.

export interface ClientOptions {
  baseUrl?: string;
  token?: string;
  fetch?: typeof fetch;
}

export class ${className} {
  private baseUrl: string;
  private token?: string;
  private fetchImpl: typeof fetch;

  constructor(opts: ClientOptions = {}) {
    this.baseUrl = opts.baseUrl ?? ${JSON.stringify(baseUrl)};
    this.token = opts.token;
    this.fetchImpl = opts.fetch ?? fetch;
  }

  private async request<T>(method: string, path: string, init: { query?: Record<string, unknown>; body?: unknown; headers?: Record<string, string> } = {}): Promise<T> {
    const url = new URL(this.baseUrl.replace(/\\/$/, '') + path);
    for (const [k, v] of Object.entries(init.query ?? {})) {
      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    }
    const headers: Record<string, string> = {
      'content-type': 'application/json',
      ...(this.token ? { authorization: \`Bearer \${this.token}\` } : {}),
      ...(init.headers ?? {}),
    };
    const res = await this.fetchImpl(url.toString(), {
      method,
      headers,
      body: init.body !== undefined ? JSON.stringify(init.body) : undefined,
    });
    if (!res.ok) throw new Error(\`${ir.title}: \${res.status} \${res.statusText}\`);
    const ct = res.headers.get('content-type') ?? '';
    return (ct.includes('application/json') ? await res.json() : await res.text()) as T;
  }

${methods}

${accessors}
}
`;

  const pkgJson = JSON.stringify(
    {
      name: opts.packageName ?? `@generated/${slug(ir.title)}-sdk`,
      version: ir.version,
      type: 'module',
      main: './client.ts',
      types: './client.ts',
    },
    null,
    2,
  );

  return [
    { path: 'client.ts', contents: client },
    { path: 'package.json', contents: pkgJson + '\n' },
  ];
}

function renderMethod(op: Operation): string {
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  const headerParams = op.parameters.filter((p) => p.in === 'header');

  const args: string[] = [];
  for (const p of pathParams) args.push(`${safe(p.name)}: string`);
  const optsParts: string[] = [];
  if (queryParams.length) optsParts.push(`query?: { ${queryParams.map((p) => `${safe(p.name)}?: ${tsType(p.schema)}`).join('; ')} }`);
  if (headerParams.length) optsParts.push(`headers?: { ${headerParams.map((p) => `${JSON.stringify(p.name)}?: string`).join('; ')} }`);
  if (op.requestBody) optsParts.push(`body${op.requestBody.required ? '' : '?'}: unknown`);
  if (optsParts.length) args.push(`opts: { ${optsParts.join('; ')} }${requiresOpts(op) ? '' : ' = {}'}`);

  const pathExpr = op.path.replace(/\{([^}]+)\}/g, (_, n) => `\${encodeURIComponent(${safe(n)})}`);
  const callParts: string[] = [];
  if (queryParams.length) {
    callParts.push(`query: { ${queryParams.map((p) => `${JSON.stringify(p.name)}: opts.query?.${safe(p.name)}`).join(', ')} }`);
  }
  if (headerParams.length) callParts.push('headers: opts.headers');
  if (op.requestBody) callParts.push('body: opts.body');
  const callOpts = callParts.length ? `, { ${callParts.join(', ')} }` : '';

  const summary = op.summary ?? op.description ?? `${op.method.toUpperCase()} ${op.path}`;
  return `  /** ${escapeComment(summary)} */
  async ${camel(op.id)}(${args.join(', ')}): Promise<unknown> {
    return this.request('${op.method.toUpperCase()}', \`${pathExpr}\`${callOpts});
  }`;
}

function requiresOpts(op: Operation): boolean {
  if (op.requestBody?.required) return true;
  return op.parameters.some((p) => (p.in === 'query' || p.in === 'header') && p.required);
}

function tsType(schema: unknown): string {
  if (!schema || typeof schema !== 'object') return 'unknown';
  const t = (schema as { type?: string }).type;
  switch (t) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return 'unknown[]';
    default: return 'unknown';
  }
}

function groupByTag(ops: Operation[]): Record<string, Operation[]> {
  const out: Record<string, Operation[]> = {};
  for (const op of ops) {
    const tag = op.tags[0] ?? 'default';
    (out[tag] ??= []).push(op);
  }
  return out;
}

function camel(s: string): string {
  return s.replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : '')).replace(/^(.)/, (_, c) => c.toLowerCase());
}
function pascal(s: string): string { return camel(s).replace(/^(.)/, (_, c) => c.toUpperCase()); }
function slug(s: string): string { return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function safe(s: string): string { return /^[a-zA-Z_$][\w$]*$/.test(s) ? s : `_${s.replace(/\W/g, '_')}`; }
function dirOf(p: string): string { const i = p.lastIndexOf('/'); return i < 0 ? '.' : p.slice(0, i); }
function escapeComment(s: string): string { return s.replace(/\*\//g, '*\\/').replace(/\n/g, ' '); }
