import { mkdir, writeFile, chmod } from 'node:fs/promises';
import { join } from 'node:path';
import type { ApiIR, Operation, Parameter } from '../core/types.js';

export interface GenerateMcpOptions {
  outDir: string;
  packageName?: string;
  defaultBaseUrl?: string;
}

export interface GeneratedFile {
  path: string;
  contents: string;
}

// Each operation becomes an MCP tool. The generated server is stdio-mode
// (single index.ts that speaks JSON-RPC over stdio per the MCP spec) and
// dispatches tool calls to the upstream REST API via fetch. We deliberately
// avoid pulling in the @modelcontextprotocol/sdk at codegen time — the
// emitted package depends on it, but our generator does not.
export async function generateMcpServer(ir: ApiIR, opts: GenerateMcpOptions): Promise<GeneratedFile[]> {
  const files = render(ir, opts);
  await mkdir(opts.outDir, { recursive: true });
  for (const f of files) {
    await mkdir(join(opts.outDir, dirOf(f.path)), { recursive: true });
    const dest = join(opts.outDir, f.path);
    await writeFile(dest, f.contents, 'utf8');
    // Make the bin entry executable so `npm i -g` installs a runnable
    // script. Without 0755, the OS refuses to exec it and the user sees
    // a confusing EACCES or "import statement" shell error instead of a
    // running MCP server. Only needed for the entry-point declared in bin.
    if (f.path === 'index.js') {
      await chmod(dest, 0o755).catch(() => {});
    }
  }
  return files;
}

function render(ir: ApiIR, opts: GenerateMcpOptions): GeneratedFile[] {
  const baseUrl = opts.defaultBaseUrl ?? ir.servers[0] ?? 'http://localhost';
  const serverName = slug(ir.title) + '-mcp';

  const tools = ir.operations.map(toolDescriptor).join(',\n');
  const handlers = ir.operations.map(toolHandler).join('\n\n');

  const index = `#!/usr/bin/env node
// AUTO-GENERATED by @profullstack/sh1pt-openapi/gen-mcp.
// Source: ${ir.title} v${ir.version}. Do not edit by hand.
//
// Stdio MCP server: each upstream API operation is exposed as one tool.
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

const BASE_URL = process.env.${envVar(ir.title)}_BASE_URL ?? ${JSON.stringify(baseUrl)};
const TOKEN = process.env.${envVar(ir.title)}_TOKEN;

const server = new Server(
  { name: ${JSON.stringify(serverName)}, version: ${JSON.stringify(ir.version)} },
  { capabilities: { tools: {} } },
);

const TOOLS = [
${tools}
];

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params;
  const a = args as Record<string, unknown>;
  switch (name) {
${handlers}
    default:
      throw new Error(\`unknown tool: \${name}\`);
  }
});

async function callApi(method, path, opts = {}) {
  const url = new URL(BASE_URL.replace(/\\/$/, '') + path);
  for (const [k, v] of Object.entries(opts.query ?? {})) {
    if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
  }
  const res = await fetch(url.toString(), {
    method,
    headers: {
      'content-type': 'application/json',
      ...(TOKEN ? { authorization: \`Bearer \${TOKEN}\` } : {}),
    },
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  });
  const ct = res.headers.get('content-type') ?? '';
  const payload = ct.includes('application/json') ? await res.json() : await res.text();
  if (!res.ok) throw new Error(\`${ir.title}: \${res.status} \${JSON.stringify(payload)}\`);
  return { content: [{ type: 'text', text: typeof payload === 'string' ? payload : JSON.stringify(payload, null, 2) }] };
}

await server.connect(new StdioServerTransport());
`;

  const pkgJson = JSON.stringify(
    {
      name: opts.packageName ?? `@generated/${slug(ir.title)}-mcp`,
      version: ir.version,
      type: 'module',
      main: './index.js',
      bin: { [serverName]: './index.js' },
      dependencies: { '@modelcontextprotocol/sdk': '^1.0.0' },
    },
    null,
    2,
  );

  const readme = `# ${ir.title} MCP server

Auto-generated from the ${ir.title} v${ir.version} OpenAPI spec. Each REST
operation is exposed as an MCP tool over stdio.

## Env

- \`${envVar(ir.title)}_BASE_URL\` (default \`${baseUrl}\`)
- \`${envVar(ir.title)}_TOKEN\` (optional bearer token)

## Tools

${ir.operations.map((op) => `- \`${op.id}\` — ${op.summary ?? op.method.toUpperCase() + ' ' + op.path}`).join('\n')}
`;

  return [
    { path: 'index.js', contents: index },
    { path: 'package.json', contents: pkgJson + '\n' },
    { path: 'README.md', contents: readme },
  ];
}

function toolDescriptor(op: Operation): string {
  const schema = inputSchema(op);
  return `  {
    name: ${JSON.stringify(op.id)},
    description: ${JSON.stringify(op.summary ?? op.description ?? op.method.toUpperCase() + ' ' + op.path)},
    inputSchema: ${JSON.stringify(schema)},
  }`;
}

function toolHandler(op: Operation): string {
  const pathExpr = op.path.replace(
    /\{([^}]+)\}/g,
    (_, n) => `\${encodeURIComponent(String(a[${JSON.stringify(n)}]))}`,
  );
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  const callParts: string[] = [];
  if (queryParams.length) callParts.push(`query: { ${queryParams.map((p) => `${JSON.stringify(p.name)}: a[${JSON.stringify(p.name)}]`).join(', ')} }`);
  if (op.requestBody) callParts.push(`body: a.body`);
  const callOpts = callParts.length ? `, { ${callParts.join(', ')} }` : '';
  return `    case ${JSON.stringify(op.id)}:
      return callApi('${op.method.toUpperCase()}', \`${pathExpr}\`${callOpts});`;
}

function inputSchema(op: Operation): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const p of op.parameters) {
    if (p.in === 'cookie') continue;
    properties[p.name] = p.schema ?? { type: 'string' };
    if (p.required) required.push(p.name);
  }
  if (op.requestBody) {
    properties.body = op.requestBody.schema ?? { type: 'object' };
    if (op.requestBody.required) required.push('body');
  }
  return { type: 'object', properties, ...(required.length ? { required } : {}) };
}

function slug(s: string): string { return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function envVar(s: string): string { return s.toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_|_$/g, ''); }
function dirOf(p: string): string { const i = p.lastIndexOf('/'); return i < 0 ? '.' : p.slice(0, i); }
