import { defineTarget, manualSetup } from '@profullstack/sh1pt-core';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

type RpmArch = 'x86_64' | 'aarch64' | 'noarch';

interface Config {
  packageName: string;        // e.g. "myapp"
  summary?: string;
  description?: string;
  license?: string;           // SPDX, e.g. "MIT"
  url?: string;               // homepage
  release?: string;           // RPM release field, default "1"
  arch?: RpmArch[];           // default ["x86_64"]
  requires?: string[];        // runtime Requires
  sourceUrl?: string;         // Source0 tarball URL
  coprProject?: string;       // "owner/project" — publish via Fedora COPR
  repoBaseUrl?: string;       // self-hosted dnf repo base URL (for the .repo file)
}

// RPM versions may not contain '-' (it separates version from release).
function rpmVersion(version: string): string {
  return version.replace(/^v/, '').replace(/-/g, '.');
}

function arches(config: Config): RpmArch[] {
  return config.arch ?? ['x86_64'];
}

function renderSpec(ctx: { version: string }, config: Config): string {
  const version = rpmVersion(ctx.version);
  const release = config.release ?? '1';
  const summary = config.summary ?? `Release package for ${config.packageName}`;
  const license = config.license ?? 'MIT';
  const buildArch = arches(config).includes('noarch') ? 'noarch' : undefined;
  const lines = [
    `Name:           ${config.packageName}`,
    `Version:        ${version}`,
    `Release:        ${release}%{?dist}`,
    `Summary:        ${summary}`,
    `License:        ${license}`,
  ];
  if (config.url) lines.push(`URL:            ${config.url}`);
  if (config.sourceUrl) lines.push(`Source0:        ${config.sourceUrl}`);
  if (buildArch) lines.push(`BuildArch:      ${buildArch}`);
  for (const req of config.requires ?? []) lines.push(`Requires:       ${req}`);
  lines.push('');
  lines.push('%description');
  lines.push(config.description ?? `${summary}. Generated by sh1pt for dnf/RPM publishing.`);
  lines.push('');
  lines.push('%prep');
  lines.push('%autosetup -n %{name}-%{version}');
  lines.push('');
  lines.push('%build');
  lines.push('# TODO: project build steps (make, cargo, go build, …)');
  lines.push('');
  lines.push('%install');
  lines.push('# TODO: install built artifacts into %{buildroot}');
  lines.push('');
  lines.push('%files');
  lines.push('# TODO: list packaged files');
  lines.push('');
  lines.push('%changelog');
  lines.push(`* Release ${version}-${release} - sh1pt <release@sh1pt.com>`);
  lines.push(`- Automated release ${version}`);
  lines.push('');
  return lines.join('\n');
}

function renderRepoFile(config: Config): string {
  const baseUrl = config.coprProject
    ? `https://download.copr.fedorainfracloud.org/results/${config.coprProject}/fedora-$releasever-$basearch/`
    : (config.repoBaseUrl ?? `https://dnf.sh1pt.com/${config.packageName}/fedora-$releasever-$basearch/`);
  return [
    `[${config.packageName}]`,
    `name=${config.packageName}`,
    `baseurl=${baseUrl}`,
    'enabled=1',
    'gpgcheck=1',
    `gpgkey=${config.repoBaseUrl ?? `https://dnf.sh1pt.com/${config.packageName}`}/RPM-GPG-KEY-${config.packageName}`,
    '',
  ].join('\n');
}

function publishCommands(ctx: { version: string }, config: Config): string[] {
  const specFile = `${config.packageName}.spec`;
  if (config.coprProject) {
    return [
      `rpmbuild -bs ${specFile}`,
      `copr-cli build ${config.coprProject} ~/rpmbuild/SRPMS/${config.packageName}-${rpmVersion(ctx.version)}-${config.release ?? '1'}*.src.rpm`,
      `copr-cli status <buildId>`,
    ];
  }
  return [
    `rpmbuild -bb ${specFile}`,
    `createrepo_c <repo-dir>`,
    `gpg --detach-sign --armor <repo-dir>/repodata/repomd.xml`,
    `rsync <repo-dir>/ ${config.repoBaseUrl ?? 'dnf.sh1pt.com:/var/www/dnf'}/`,
  ];
}

export default defineTarget<Config>({
  id: 'pkg-dnf',
  kind: 'package-manager',
  label: 'dnf repo / Fedora COPR',
  async build(ctx, config) {
    const specPath = join(ctx.outDir, 'rpm', `${config.packageName}.spec`);
    const repoPath = join(ctx.outDir, 'rpm', `${config.packageName}.repo`);
    ctx.log(`generate RPM spec for ${config.packageName} v${ctx.version} [${arches(config).join(', ')}]`);
    await mkdir(dirname(specPath), { recursive: true });
    await Promise.all([
      writeFile(specPath, renderSpec(ctx, config), 'utf-8'),
      writeFile(repoPath, renderRepoFile(config), 'utf-8'),
    ]);
    return {
      artifact: specPath,
      meta: { specFile: specPath, repoFile: repoPath, commands: publishCommands(ctx, config) },
    };
  },
  async ship(ctx, config) {
    const via = config.coprProject ? `COPR ${config.coprProject}` : (config.repoBaseUrl ?? 'dnf.sh1pt.com');
    ctx.log(`publish ${config.packageName}@${ctx.version} to ${via}`);
    if (ctx.dryRun) return { id: 'dry-run', meta: { commands: publishCommands(ctx, config) } };
    if (config.coprProject) {
      if (!ctx.secret('COPR_API_TOKEN')) {
        throw new Error('COPR_API_TOKEN not in vault — run: sh1pt secret set COPR_API_TOKEN <token from https://copr.fedorainfracloud.org/api/>');
      }
    } else if (!ctx.secret('DNF_GPG_KEY')) {
      throw new Error('DNF_GPG_KEY not in vault — run: sh1pt secret set DNF_GPG_KEY "$(gpg --export-secret-keys --armor <key-id>)"');
    }
    // Live publish (rpmbuild + copr-cli build | createrepo_c + GPG-sign + upload)
    // is not implemented yet — fail loudly rather than report a false success.
    throw new Error(
      `pkg-dnf live publish for ${config.packageName} is not implemented yet — ` +
      `use dryRun to preview the ${config.coprProject ? 'rpmbuild + copr-cli' : 'rpmbuild + createrepo_c'} commands.`,
    );
  },
  async status(id) {
    const name = id.split('@')[0] ?? id;
    return { state: 'in-review', url: `https://dnf.sh1pt.com/${name}/` };
  },
  setup: manualSetup({
    label: 'dnf repo / Fedora COPR',
    vendorDocUrl: 'https://rpm-packaging-guide.github.io/',
    steps: [
      'COPR (hosted): create an account at https://copr.fedorainfracloud.org and a project.',
      'COPR: copy the API token from https://copr.fedorainfracloud.org/api/ and run: sh1pt secret set COPR_API_TOKEN <token>',
      'Self-hosted: generate a signing key (gpg --full-generate-key) and run: sh1pt secret set DNF_GPG_KEY "$(gpg --export-secret-keys --armor <key-id>)"',
      'Self-hosted: run: sh1pt secret set DNF_GPG_PASSPHRASE <passphrase>',
      'Build needs rpmbuild + createrepo_c (or copr-cli) installed on a Fedora/RHEL-like host.',
    ],
  }),
});
