import { planRemoteDiff, hasRemoteConflicts, type RemoteDiffPlan, type RemoteFileInfo } from '../diff/plan.js';
import type { ActionPackManifest } from '../action-pack/schema.js';
import type { RenderResult } from '../action-pack/render.js';
import {
  createBranch,
  createPullRequest,
  encodeBase64,
  getBranchSha,
  getFile,
  getRepo,
  upsertFile,
  type GithubClientOptions,
} from './github-api.js';

export interface OpenPrOptions {
  client: GithubClientOptions;
  owner: string;
  repo: string;
  manifest: ActionPackManifest;
  render: RenderResult;
  /** Base branch to fork from. Defaults to the repo's default_branch. */
  baseBranch?: string;
  /** Branch name to create. Defaults to `sh1pt/actions/<pack-id>/<timestamp>`. */
  branchName?: string;
  /** Open as a draft PR. */
  draft?: boolean;
  /** Overwrite existing unmanaged / other-pack files. Off by default. */
  force?: boolean;
  /** PR title/body overrides (defaults derived from the pack manifest). */
  title?: string;
  body?: string;
}

export type OpenPrOutcome =
  | { kind: 'unchanged'; reason: string }
  | { kind: 'conflict'; plan: RemoteDiffPlan; reason: string }
  | { kind: 'opened'; plan: RemoteDiffPlan; pullRequestUrl: string; number: number; branch: string }
  | { kind: 'error'; error: string; status: number };

function shortTimestamp(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;
}

function defaultBranchName(packId: string): string {
  return `sh1pt/actions/${packId}/${shortTimestamp()}`;
}

function defaultTitle(manifest: ActionPackManifest): string {
  return `sh1pt: install ${manifest.name} (${manifest.id}@${manifest.version})`;
}

function defaultBody(manifest: ActionPackManifest, plan: RemoteDiffPlan): string {
  const fileLines = plan.files.map((f) => {
    const verb =
      f.status.kind === 'create'
        ? 'create'
        : f.status.kind === 'update-managed'
          ? 'update'
          : f.status.kind === 'unchanged'
            ? 'unchanged'
            : 'conflict';
    return `- \`${f.destination}\` — ${verb}`;
  });
  const secretLines = manifest.secrets.length
    ? manifest.secrets.map((s) => `- \`${s.name}\`${s.description ? ` — ${s.description}` : ''}`).join('\n')
    : '_No new secrets required._';
  return [
    `# sh1pt Actions Fleet: install ${manifest.name}`,
    '',
    `Installs **${manifest.name}** (\`${manifest.id}@${manifest.version}\`) from the sh1pt Actions Store.`,
    '',
    '## Files',
    fileLines.join('\n'),
    '',
    '## Required secrets',
    secretLines,
    '',
    '## Notes',
    '- Generated workflow files include a managed comment with a sha256 of the rendered body, so future updates can be detected without overwriting hand-edits.',
    '- Install mode: pull request (no direct commits).',
    '- Rollback: close this PR or revert the merge commit.',
    '',
    '---',
    '',
    '_Generated by sh1pt Actions Fleet._',
  ].join('\n');
}

export async function openPackPullRequest(options: OpenPrOptions): Promise<OpenPrOutcome> {
  const { client, owner, repo, manifest, render } = options;

  // Resolve base branch.
  let baseBranch = options.baseBranch;
  if (!baseBranch) {
    const repoInfo = await getRepo(client, owner, repo);
    if (!repoInfo.ok || !repoInfo.data) {
      return { kind: 'error', error: repoInfo.error ?? 'repo lookup failed', status: repoInfo.status };
    }
    baseBranch = repoInfo.data.default_branch;
  }

  // Read existing files at the base ref to plan the diff.
  async function readExisting(destinationPath: string): Promise<RemoteFileInfo | null> {
    const result = await getFile(client, owner, repo, destinationPath, baseBranch!);
    if (!result.ok) {
      // Surface unexpected non-404 errors. 404 already maps to null upstream.
      throw new Error(`getFile(${destinationPath}) failed: ${result.error}`);
    }
    return result.data;
  }

  const plan = await planRemoteDiff({
    owner,
    repo,
    baseRef: baseBranch,
    render,
    readExisting,
  });

  const allUnchanged = plan.files.every((f) => f.status.kind === 'unchanged');
  if (allUnchanged) {
    return { kind: 'unchanged', reason: 'all files already match the latest pack version' };
  }

  if (hasRemoteConflicts(plan) && !options.force) {
    const conflicted = plan.files
      .filter((f) => f.status.kind === 'conflict-unmanaged' || f.status.kind === 'conflict-other-pack')
      .map((f) => f.destination)
      .join(', ');
    return {
      kind: 'conflict',
      plan,
      reason: `conflict on ${conflicted} — pass --force to overwrite`,
    };
  }

  // Get base SHA and create the working branch.
  const baseShaResult = await getBranchSha(client, owner, repo, baseBranch);
  if (!baseShaResult.ok || !baseShaResult.data) {
    return { kind: 'error', error: baseShaResult.error ?? 'base sha lookup failed', status: baseShaResult.status };
  }

  const branchName = options.branchName ?? defaultBranchName(manifest.id);
  const created = await createBranch(client, owner, repo, branchName, baseShaResult.data);
  if (!created.ok) {
    return { kind: 'error', error: created.error ?? 'branch create failed', status: created.status };
  }

  // Upsert each file that isn't already unchanged.
  for (const file of plan.files) {
    if (file.status.kind === 'unchanged') continue;
    const message = file.existingSha
      ? `Update ${file.destination} via sh1pt ${manifest.id}@${manifest.version}`
      : `Add ${file.destination} via sh1pt ${manifest.id}@${manifest.version}`;
    const body: { message: string; content: string; branch: string; sha?: string } = {
      message,
      content: encodeBase64(file.newContent),
      branch: branchName,
    };
    if (file.existingSha) body.sha = file.existingSha;
    const upserted = await upsertFile(client, owner, repo, file.destination, body);
    if (!upserted.ok) {
      return {
        kind: 'error',
        error: `upsert ${file.destination} failed: ${upserted.error ?? 'unknown'}`,
        status: upserted.status,
      };
    }
  }

  // Open the PR.
  const pr = await createPullRequest(client, owner, repo, {
    title: options.title ?? defaultTitle(manifest),
    head: branchName,
    base: baseBranch,
    body: options.body ?? defaultBody(manifest, plan),
    draft: options.draft ?? false,
  });
  if (!pr.ok || !pr.data) {
    return { kind: 'error', error: pr.error ?? 'createPullRequest failed', status: pr.status };
  }

  return {
    kind: 'opened',
    plan,
    pullRequestUrl: pr.data.html_url,
    number: pr.data.number,
    branch: branchName,
  };
}
