import { contractTestDocs } from '@profullstack/sh1pt-core/testing';
import { access, chmod, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import docs from './index.js';

contractTestDocs(docs, {
  sampleConfig: { theme: 'default' },
  sampleSpec: {
    kind: 'pitch-deck',
    title: 'test deck',
    format: 'pptx',
    markdown: '# slide 1\n\n---\n\n# slide 2',
  },
});

const tmpDir = join(process.cwd(), '.tmp', 'docs-marp-tests');
const originalPath = process.env.PATH;

afterEach(async () => {
  process.env.PATH = originalPath;
  await rm(tmpDir, { recursive: true, force: true });
});

describe('docs-marp', () => {
  it('keeps dry-run side-effect free', async () => {
    await expect(docs.generate({
      secret: () => undefined,
      log: () => {},
      dryRun: true,
    }, {
      kind: 'sales-deck',
      title: 'dry deck',
      format: 'pdf',
      markdown: '# Dry',
    }, {
      outDir: tmpDir,
      theme: 'gaia',
    })).resolves.toEqual({
      id: 'dry-run',
      format: 'pdf',
      localPath: join(tmpDir, 'sales-deck.pdf'),
    });

    await expect(access(join(tmpDir, 'sales-deck.md'))).rejects.toThrow();
  });

  it('writes markdown and invokes the Marp CLI with the selected format', async () => {
    const argsPath = await installFakeMarp();

    await expect(docs.generate({
      secret: () => undefined,
      log: () => {},
      dryRun: false,
    }, {
      kind: 'pitch-deck',
      title: 'Launch',
      format: 'pptx',
      markdown: '# Launch\n\n---\n\n# Demo',
    }, {
      outDir: tmpDir,
      theme: 'uncover',
      allowLocalFiles: true,
    })).resolves.toEqual({
      id: 'marp_pitch-deck_pptx',
      format: 'pptx',
      localPath: join(tmpDir, 'pitch-deck.pptx'),
    });

    await expect(readFile(join(tmpDir, 'pitch-deck.md'), 'utf-8')).resolves.toBe('# Launch\n\n---\n\n# Demo');
    await expect(readFile(join(tmpDir, 'pitch-deck.pptx'), 'utf-8')).resolves.toBe('generated by fake marp');
    await expect(readFile(argsPath, 'utf-8').then(JSON.parse)).resolves.toEqual([
      join(tmpDir, 'pitch-deck.md'),
      '--pptx',
      '--output',
      join(tmpDir, 'pitch-deck.pptx'),
      '--theme',
      'uncover',
      '--allow-local-files',
    ]);
  });

  it('surfaces a clear install hint when Marp is missing', async () => {
    await mkdir(join(tmpDir, 'empty-bin'), { recursive: true });
    process.env.PATH = join(tmpDir, 'empty-bin');

    await expect(docs.generate({
      secret: () => undefined,
      log: () => {},
      dryRun: false,
    }, {
      kind: 'proposal',
      title: 'Proposal',
      format: 'html',
      markdown: '# Proposal',
    }, {
      outDir: tmpDir,
    })).rejects.toThrow('npm install -g @marp-team/marp-cli');
  });

  it('rejects unsupported formats before writing files', async () => {
    await expect(docs.generate({
      secret: () => undefined,
      log: () => {},
      dryRun: false,
    }, {
      kind: 'whitepaper',
      title: 'Whitepaper',
      format: 'docx',
      markdown: '# Whitepaper',
    }, {
      outDir: tmpDir,
    })).rejects.toThrow('docs-marp does not support docx');

    await expect(access(join(tmpDir, 'whitepaper.md'))).rejects.toThrow();
  });
});

async function installFakeMarp(): Promise<string> {
  const binDir = join(tmpDir, 'bin');
  const marpPath = join(binDir, 'marp');
  const argsPath = join(tmpDir, 'marp-args.json');

  await mkdir(binDir, { recursive: true });
  await writeExecutable(marpPath, `#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const args = process.argv.slice(2);
fs.writeFileSync(${JSON.stringify(argsPath)}, JSON.stringify(args));
const outputFlag = args.indexOf('--output');
if (outputFlag === -1 || !args[outputFlag + 1]) process.exit(2);
fs.mkdirSync(path.dirname(args[outputFlag + 1]), { recursive: true });
fs.writeFileSync(args[outputFlag + 1], 'generated by fake marp');
`);

  process.env.PATH = `${binDir}:${originalPath ?? ''}`;
  return argsPath;
}

async function writeExecutable(path: string, source: string): Promise<void> {
  await writeFile(path, source, 'utf-8');
  await chmod(path, 0o755);
}
